name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ['CI Pipeline']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Deploy to GitHub Pages
        run: npm run deploy
